#!/bin/bash
#=========================================================
#	buildsimpl
#
# Description:
# Master build script for SIMPL tree
#
#-----------------------------------------------------------------------
#    Copyright (C) 2006 SIMPL Open Source Project. 
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    If you discover a bug or add an enhancement contact us on the: 
#
#	SIMPL project mailing list
#-----------------------------------------------------------------------
#
# $Log: buildsimpl,v $
# Revision 1.7  2012/10/30 20:09:41  bobfcsoft
# added FLAVOR define
#
# Revision 1.6  2011/09/08 16:18:23  bobfcsoft
# added support for CYGWIN
#
# Revision 1.5  2011/03/23 16:33:43  bobfcsoft
# added OS_TYPE for Mac stuff
#
# Revision 1.4  2008/11/27 20:32:04  johnfcsoft
# clobber-->clean
#
# Revision 1.3  2008/11/13 22:40:44  bobfcsoft
# separate make.out files
#
# Revision 1.2  2006/08/14 18:33:02  bobfcsoft
# split out tcl and python stuff
#
# Revision 1.1.1.1  2005/03/27 11:50:35  paul_c
# Initial import
#
# Revision 1.13  2005/02/09 13:17:29  root
# changed email contact address
#
# Revision 1.12  2003/10/06 18:05:20  root
# more integrate Python build
#
# Revision 1.11  2003/06/24 17:51:03  root
# added Python check
#
# Revision 1.10  2003/04/23 20:41:40  root
# added support for dynamic libraries
#
# Revision 1.9  2002/12/02 15:57:51  root
# better handling of TCLVER options
#
# Revision 1.8  2002/11/22 16:19:36  root
# 2.0rc3
#
# Revision 1.7  2002/08/28 12:20:21  root
# full path for createIPCtable
#
# Revision 1.6  2002/07/14 11:43:02  root
# explicit path to tclver added
#
# Revision 1.5  2002/07/07 11:07:13  root
# added a step to create the slot table
#
# Revision 1.4  2002/06/12 18:10:47  root
# added simpl version to script
#
# Revision 1.3  2002/01/31 14:45:16  root
# trap Tcl/Tk 8.3 dependancy
#
# Revision 1.2  2000/10/13 13:48:34  root
# using SIMPL_HOME
#
# Revision 1.1  2000/04/17 15:09:13  root
# Initial revision
#
#
#=========================================================


if [ -z $FIFO_PATH ]
then
	echo "The SIMPL code uses an environment variable"
	echo "called FIFO_PATH to locate the directory"
	echo "into which all the fifos will be created."
	echo "Please export the FIFO_PATH environment variable"
	echo "before continuing."
	exit
else
if [ ! -d $FIFO_PATH ]
then
	echo "The $FIFO_PATH directory does not exist."
	echo "The SIMPL code build requires this directory to"
	echo "exist in order to setup a memory mapped file."
	echo "Please create $FIFO_PATH before continuing."
	exit
else
if [ -z $SIMPL_HOME ]
then
	echo "The SIMPL code uses an environment variable"
	echo "called SIMPL_HOME to locate the SIMPL code tree."
	echo "The SIMPL_HOME can point any place as long as the"
	echo "path it points to ends in \"/simpl\"."
	echo "Please export the SIMPL_HOME environment variable"
	echo "before continuing."
	exit
else
if [ ! -d $SIMPL_HOME ]
then
	echo "The $SIMPL_HOME directory does not exist."
	echo "This indicates that the SIMPL tar.gz was improperly"
	echo "installed."
	echo "Please reexamine the installation instructions and"
	echo "repeat the installation if necessary."
	exit
fi
fi
fi
fi

FLAVOR=_STABLE
MYOS=`uname | cut -c1-6`

if [ $MYOS == "Darwin" ]
then
	OS_TYPE=_MAC_OS_X
else
if [ $MYOS == "CYGWIN" ]
then
	OS_TYPE=_CYGWIN
	FLAVOR=_EXPMTL
	echo "SIMPL-Cygwin requires that the cygserver be running"
	echo "in the background to manage shared memory."
	echo "Please be sure this is the case before continuing."
else
	OS_TYPE=_LINUX_OS
fi
fi

OUT_FILE=$SIMPL_HOME/make.out

cd $SIMPL_HOME
rm make.out.gz

date > $OUT_FILE
echo "==================================================" >> $OUT_FILE
echo "SIMPL_HOME = $SIMPL_HOME" >> $OUT_FILE
echo "FIFO_PATH = $FIFO_PATH" >> $OUT_FILE
echo "SIMPL version:" >> $OUT_FILE
cat $SIMPL_HOME/version >> $OUT_FILE
echo "OS_TYPE = $OS_TYPE" >> $OUT_FILE

echo "=================================================="
echo "SIMPL top level build script"
echo ""
echo "This script will run a top level Makefile"
echo "and route its output to a file:"
echo "     $OUT_FILE"
echo ""
echo "you can watch the process by"
echo "running tail -f $OUT_FILE on another console"
echo "if you wish"
echo "=================================================="
sleep 5 

echo "=================================================="
echo "Step 1:"
echo "running make clean ... please wait"
echo "NOTE: missing file errors here are quite normal"
echo "especially the first time you run this"
sleep 2
echo "==================================================" >> $OUT_FILE
echo "running make clean" >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
cd $SIMPL_HOME
make clean 1>>$OUT_FILE 2>&1

if [ $# = 1 ]
then
	if [ $1 = "dynamic" ]
	then
		echo "=================================================="
		echo "Step 2:"
		echo "running make dynamic ... please wait"
		echo "==================================================" >> $OUT_FILE
		echo "running make dynamic" >> $OUT_FILE
		echo "==================================================" >> $OUT_FILE
		make dynamic OS_TYPE=$OS_TYPE FLAVOR=$FLAVOR 1>>$OUT_FILE 2>&1
		echo "SIMPL make dynamic done"
	fi
else
	echo "=================================================="
	echo "Step 2:"
	echo "running make install ... please wait"
	echo "==================================================" >> $OUT_FILE
	echo "running make install" >> $OUT_FILE
	echo "==================================================" >> $OUT_FILE
	make install OS_TYPE=$OS_TYPE FLAVOR=$FLAVOR 1>>$OUT_FILE 2>&1
	echo "SIMPL make install done"
fi

echo "=================================================="
echo "Step 3:"
echo "taking a snapshot of the $SIMPL_HOME/bin ... please wait"

cd $SIMPL_HOME/bin
echo "==================================================" >> $OUT_FILE
pwd >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
echo "snapshot of $SIMPL_HOME/bin using \"ls -tl\"" >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
ls -tl >>$OUT_FILE
echo "==================================================" >> $OUT_FILE
echo "snapshot of $SIMPL_HOME/bin using \"cksum *\"" >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
cksum * >>$OUT_FILE

echo "=================================================="
echo "Step 4:"
echo "taking a snapshot of the $SIMPL_HOME/lib ... please wait"

cd $SIMPL_HOME/lib
echo "==================================================" >> $OUT_FILE
pwd >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
echo "snapshot of $SIMPL_HOME/lib using \"ls -tl\"" >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
ls -tl >>$OUT_FILE
echo "==================================================" >> $OUT_FILE
echo "snapshot of $SIMPL_HOME/lib using \"cksum *\"" >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
cksum * >>$OUT_FILE

echo "=================================================="
echo "Step 5:"
echo "Please examine the output from the Makefile at:"
echo "	$OUT_FILE"
echo ""
echo "======================================================="
echo "If you encountered build problems that you cannot solve"
echo "Please email $OUT_FILE.gz to the SIMPL project"
echo "======================================================="
echo "==================================================" >> $OUT_FILE
date >> $OUT_FILE
echo "==================================================" >> $OUT_FILE
