#! /bin/bash
#=========================================================
#	simpl_init
#
# Description:
# initialize essential simpl items
#
#-----------------------------------------------------------------------
#    Copyright (C) 2002 FCSoftware Inc. 
#
#    This library is free software; you can redistribute it and/or
#    modify it under the terms of the GNU Lesser General Public
#    License as published by the Free Software Foundation; either
#    version 2.1 of the License, or (at your option) any later version.
#
#    This library is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#    Lesser General Public License for more details.
#
#    You should have received a copy of the GNU Lesser General Public
#    License along with this library; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    If you discover a bug or add an enhancement here's how to reach us: 
#
#	fcsoft@netcom.ca
#-----------------------------------------------------------------------
#
# $Log: simpl_init,v $
# Revision 1.1.1.1  2005/03/27 11:50:35  paul_c
# Initial import
#
# Revision 1.1  2002/10/25 19:05:11  root
# Initial revision
#
#-----------------------------------------------------------------------
#
			
if [ -z $FIFO_PATH ]
then
	echo "The SIMPL code uses an environment variable"
	echo "called FIFO_PATH to locate the directory"
	echo "into which all the fifos will be created."
	echo "Please export the FIFO_PATH environment variable"
	echo "before continuing."
	exit
else
if [ ! -d $FIFO_PATH ]
then
	echo "The $FIFO_PATH directory does not exist."
	echo "Please create $FIFO_PATH before continuing."
	exit
else
# remove all fifos from that directory

cd $FIFO_PATH
for filename in `ls`
do
	if [ -p $filename ]
	then
		echo "cleaning up fifo $filename"
		rm $filename
	fi
done

fi
fi
