#!/bin/bash
#
#$Log: runtest,v $
#Revision 1.1  2006/04/24 22:01:37  bobfcsoft
#new test
#
#

TEST_NO=s0003
TEST_DESC="SIMPL benchmark via loopback with proxy"

TEST_DIR=$TEST_HOME/testing/test$TEST_NO
OUTFILE=$TEST_DIR/results/test.out

echo "Starting up test $TEST_NO" | tee $OUTFILE
echo $TEST_DESC | tee -a $OUTFILE
date | tee -a $OUTFILE

echo "" | tee -a $OUTFILE
echo "This may take a while to complete ... please wait" | tee -a $OUTFILE
echo "" | tee -a $OUTFILE

cd $SIMPL_HOME/bin
protocolRouter &
surrogateTcp -b 9001 &

cd $SIMPL_HOME/surrogates/tcp/test
surroProxy.tcl -p 9001 &

cd $SIMPL_HOME/benchmarks/bin
cksum receiver | tee -a $OUTFILE
receiver -n BOBR &


cksum sender | tee -a $OUTFILE
sender -n BOBS -r 127.0.0.1:BOBR -t 10 -s 1024 | tee -a $OUTFILE

echo "hit any key to exit"
read ans

fcslay BOBR
fcslay PROXY
killall surrogateTcp
killall protocolRouter
echo "Test finished you can run posttest $TEST_NO for result"
